version: "3.9"
services:
 plantcare-service:
  image: heridder/plantcare
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: